---
abstract: 'Perl on a Stick (EXPERIMENTAL)'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Portable
no_index:
  directory:
    - inc
    - t
requires:
  File::Spec: 0.80
  List::Util: 1.19
  Parse::CPAN::Meta: 0.03
  perl: 5.8.0
version: 0.05
